/*
 * Formbuilder API
 *
 * This is the documentation for the Formbuilder API's
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Screen struct {
	Id int32 `json:"id,omitempty"`
	Uid string `json:"uid,omitempty"`
	Name string `json:"name,omitempty"`
	CreatedAt int32 `json:"created_at,omitempty"`
	CreatedBy int32 `json:"created_by,omitempty"`
	UpdatedAt int32 `json:"updated_at,omitempty"`
	UpdatedBy int32 `json:"updated_by,omitempty"`
	AccountId int32 `json:"account_id,omitempty"`
	Status string `json:"status,omitempty"`
}
