/*
 * Formbuilder API
 *
 * This is the documentation for the Formbuilder API's
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateScreenRequest struct {
	Name string `json:"name,omitempty"`
}
