/*
 * Formbuilder API
 *
 * This is the documentation for the Formbuilder API's
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateScreenRequest struct {
	Name string `json:"name,omitempty"`
	Definition *interface{} `json:"definition,omitempty"`
	HasDefinition bool `json:"has_definition,omitempty"`
}
