/*
 * Formbuilder API
 *
 * This is the documentation for the Formbuilder API's
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200Data struct {
	Screens *[]Screen `json:"screens,omitempty"`
	TotalCount int32 `json:"total_count,omitempty"`
}
